config/routes.rb
Reportingwheel::Application.routes.draw do
    match 'logout' => 'user_sessions#destroy', :as => 'logout'
    match 'home' => 'home#index', :as => 'home'

    match 'user_sessions' => 'user_sessions#create'
    
    resources :user_sessions, :users
    

  root :to => "wheel#index"
  

  match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Reporting Wheel</title>

	<link href="/stylesheets/styles.css" rel="stylesheet" type="text/css" />
	<link href="/stylesheets/jquery.jgrowl.css" rel="stylesheet" type="text/css" />

	<%= javascript_include_tag 'application', 'jquery-1.4.2.min', 'jquery.jgrowl.min' %>

	<% if !flash[:notice].nil? %>
	<script type="text/javascript">
		$(function() {
			$.jGrowl('<%= flash[:notice] %>');
		});
	</script>
	<% end %>

	<%= yield :head %>
</head>
<body>
<div id="Container">
	<div id="Main">
	    <div id="Content_container">
	        <div id="Header">
	            <a href="/"><div id="Logo" title="Reporting Wheel"></div><!-- /Logo --></a>
				<% if logged_in? %>
					<div id="User">
						<b><%= current_user.username %></b>
						<br />
						<span><%= link_to "Settings", edit_user_path(:current) %> | <%= link_to 'Logout', logout_url %></span>
					</div>
				<% end %>
	        </div><!-- /Header -->
	        <div id="Content">
				<%= content_for?(:content) ? yield(:content) : yield %>
	        </div><!-- /Content -->
	    </div><!-- /Content_container -->
	</div><!-- /Main -->
	<div id="Separator"></div>
	<div id="Footer">
		<div id="FooterContent">
			&copy; 2014 Reporting Wheel<div id="version">Version: <%= app_version %></div>
		</div>
	</div><!-- /Footer -->
</div>
</body>
</html>